###### Different Terms for Input - Add vs Multiply

In [5]:
#O(n + n) = O(2n) :: we can easily drop the constants : O(n) time complexity
def print_items(n):
    #O(n)
    for i in range(n):
        print(i)
    #O(n)
    for j in range(n):
        print(j)

In [ ]:
#O(a + b) time complexity :: We can't say a=n & b=n | coz what if a=1 and b=Million
def print_items(a, b):
    #O(a)
    for i in range(a):
        print(i)
    #O(b)
    for j in range(b):
        print(j)

In [ ]:
#O(a * b) time complexity 
def print_items(a, b):
    #O(a * b)
    for i in range(a):
        for j in range(b):
            print(j)

###### How to measure the codes using Big O?

|No|Description|Complexity|
|--|-----------|----------|
|Rule 1|Any assignment statements and if statements that are executed once regardless of the size of the problem| O(1)|
|Rule 2|A simple "for" loop from 0 to n (with no internal loops)| O(n)|
|Rule 3|A nested loop of the same type takes quadratic time complexity| O(n^2)|
|Rule 4|A loop, in which the controlling parameter is divided by two at each step| O(logN)|
|Rule 5|When dealing with multiple statements, just add them up| |


In [6]:
# O(1) + O(n) + (O(1)+O(1)) + O(1) :: O(1) + (O(n) + O(1)) + O(1) : O(1) + O(n) + O(1) => O(n) time complexity
# O(1)+O(1) = 2O(1) : Remove constant terms = O(1)
# O(n)+O(1) = O(n) : coz we learnt to remove non-dominant term, and here O(n) is dominant term
def findBiggestNumber(sampleArray):
    #O(1)
    biggestNumber = sampleArray[0]
    #O(n)
    for index in range(1, len(sampleArray)):
    #O(1)
        if sampleArray[index] > biggestNumber:
    #O(1)
            biggestNumber = sampleArray[index]
    #O(1)
    print(biggestNumber)

## Section 3: Arrays
Advantages of array model is that it is more memory efficient than the list for storing the large types of the same data type.

##### Create an Array

In [6]:
import array
#Empty Array :: time complexity = O(1), space complexity = O(1)
my_array = array.array('i')
print(my_array)
#time complexity = O(n), space complexity = O(n)
my_array1 = array.array('i',[1,2,3,4])
print(my_array1)

array('i')
array('i', [1, 2, 3, 4])


In [12]:
import numpy as np
#Empty Array :: time complexity = O(1), space complexity = O(1)
np_array = np.array([], dtype=int)
print(np_array)
#time complexity = O(n), space complexity = O(n)
np_array1 = np.array([1,2,3,4])
print(np_array1)

[]
[1 2 3 4]


##### Insertion to Array

When we are insterting an element at a specific position using insert method,   
**time complexity** = depends on the number of the elements that needs to be shifted right = O(n)  
**space complexity** = O(1)

In [7]:
my_array1.insert(0,6)
my_array1.insert(10,7)
my_array1

array('i', [6, 1, 2, 3, 4, 7])

#### Traversal Operation
**time complexity** = O(n)   
**space complexity** = O(1), coz we don't need extra location to perform this operation.

In [8]:
#O(n) + O(1) = O(n)
def traverseArray(array):
    #O(n)
    for i in array:
        #O(1)
        print(i)

#### Accessing an element of Array
**time complexity** = O(1)  
**space complexity** = O(1)

In [9]:
#O(1)
def accessElement(array, index):
    #O(1)
    if index >= len(array):
        #O(1)
        print('Len is outside array length')
    else:
        #O(1)
        print(array[index])

#### Searching for an element of Array
**time complexity** = O(1)  
**space complexity** = O(1)

In [11]:
import array
my_array1 = array.array('i', [1,2,3,4,5])

def linear_search(arr, target):
    #O(1) = coz range function doesn't generate seq of integers, rather creates an iterator that can be used to produce numbers on demand.
    for i in range(len(arr)):
        #O(1)
        if arr[i] == target:
            #O(1)
            return i
    #O(1)
    return -1

print(linear_search(my_array1, 5))

4


#### Deleting an element from Array
When we delete an element form array, the next element will move to the place of deleted element and so on.  
**time complexity** = if last element : O(1) else O(n)  
**space complexity** = O(1)

#### Time and space complexity of One dimensional array
|            Operation               | Time Complexity | Space Complexity |
|------------------------------------|-----------------|------------------|
|Creating an empty array | O(1) | O(1) |
|Creating an array with elements | O(n) | O(n) |
|Inserting a value in an array | O(n) | O(1) |
|Traversing a given array | O(n) | O(1) |
|Accessing a given cell | O(1) | O(1) |
|Searching a given value | O(n) | O(1) |
|Deleting a given value | O(n) | O(1) |

In [19]:
from array import *

# 1. Create an array and traverse. 

my_array = array('i',[1,2,3,4,5])

for i in my_array:
    print(i)


# 2. Access individual elements through indexes
print("Step 2")
print(my_array[3])

# 3. Append any value to the array using append() method

print("Step 3")
my_array.append(6)
print(my_array)

# 4. Insert value in an array using insert() method
print("Step 4")
my_array.insert(3, 11)
print(my_array)


# 5. Extend python array using extend() method
print("Step 5")
my_array1 = array('i', [10,11,12])
my_array.extend(my_array1)
print(my_array)

# 6. Add items from list into array using fromlist() method
print("Step 6")
tempList = [20,21,22]
my_array.fromlist(tempList)
print(my_array)

# 7. Remove any array element using remove() method
print("Step 7")
my_array.remove(11)
print(my_array)

# 8. Remove last array element using pop() method
print("Step 8")
my_array.pop()
print(my_array)

# 9. Fetch any element through its index using index() method
print("Step 9")
print(my_array.index(21))

# 10. Reverse a python array using reverse() method
print("Step 10")
my_array.reverse()
print(my_array)

# 11. Get array buffer information through buffer_info() method
print("Step 11")
print(my_array.buffer_info())

# 12. Check for number of occurrences of an element using count() method
print("Step 12")
my_array.append(11)
print(my_array.count(11))
print(my_array)

# 13. Convert array to string using tostring() method
print("Step 13")
strTemp = my_array.tobytes()
print(strTemp)
ints = array('i')
ints.frombytes(strTemp)
print(ints)

# 14. Convert array to a python list with same elements using tolist() method
print("Step 14")
print(my_array.tolist())

# 15. Append a string to char array using fromstring() method


# 16. Slice Elements from an array
print("Step 16")
print(my_array[:])

1
2
3
4
5
Step 2
4
Step 3
array('i', [1, 2, 3, 4, 5, 6])
Step 4
array('i', [1, 2, 3, 11, 4, 5, 6])
Step 5
array('i', [1, 2, 3, 11, 4, 5, 6, 10, 11, 12])
Step 6
array('i', [1, 2, 3, 11, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 7
array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 8
array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21])
Step 9
10
Step 10
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])
Step 11
(139710998894192, 11)
Step 12
2
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])
Step 13
b'\x15\x00\x00\x00\x14\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x0b\x00\x00\x00'
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])
Step 14
[21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11]
Step 16
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])


### Two Dimensional Array
An array with a bunch of values having been declared with double index.

In [1]:
#O(mn), m= col, n=rows
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


#### Insertion
Addition of column / Addition of rows  
**Time complexity** = O(MN) = M: number of columns, N: number of rows

In [6]:
#O(mn), m= col, n=rows
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

newTwoDArray = np.insert(twoDArray, 0, [[1, 2, 3, 4]], axis=1)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]
