###### Different Terms for Input - Add vs Multiply

In [5]:
#O(n + n) = O(2n) :: we can easily drop the constants : O(n) time complexity
def print_items(n):
    #O(n)
    for i in range(n):
        print(i)
    #O(n)
    for j in range(n):
        print(j)

In [ ]:
#O(a + b) time complexity :: We can't say a=n & b=n | coz what if a=1 and b=Million
def print_items(a, b):
    #O(a)
    for i in range(a):
        print(i)
    #O(b)
    for j in range(b):
        print(j)

In [ ]:
#O(a * b) time complexity 
def print_items(a, b):
    #O(a * b)
    for i in range(a):
        for j in range(b):
            print(j)

###### How to measure the codes using Big O?

|No|Description|Complexity|
|--|-----------|----------|
|Rule 1|Any assignment statements and if statements that are executed once regardless of the size of the problem| O(1)|
|Rule 2|A simple "for" loop from 0 to n (with no internal loops)| O(n)|
|Rule 3|A nested loop of the same type takes quadratic time complexity| O(n^2)|
|Rule 4|A loop, in which the controlling parameter is divided by two at each step| O(logN)|
|Rule 5|When dealing with multiple statements, just add them up| |


In [6]:
# O(1) + O(n) + (O(1)+O(1)) + O(1) :: O(1) + (O(n) + O(1)) + O(1) : O(1) + O(n) + O(1) => O(n) time complexity
# O(1)+O(1) = 2O(1) : Remove constant terms = O(1)
# O(n)+O(1) = O(n) : coz we learnt to remove non-dominant term, and here O(n) is dominant term
def findBiggestNumber(sampleArray):
    #O(1)
    biggestNumber = sampleArray[0]
    #O(n)
    for index in range(1, len(sampleArray)):
    #O(1)
        if sampleArray[index] > biggestNumber:
    #O(1)
            biggestNumber = sampleArray[index]
    #O(1)
    print(biggestNumber)

## Section 3: Arrays
Advantages of array model is that it is more memory efficient than the list for storing the large types of the same data type.

##### Create an Array

In [6]:
import array
#Empty Array :: time complexity = O(1), space complexity = O(1)
my_array = array.array('i')
print(my_array)
#time complexity = O(n), space complexity = O(n)
my_array1 = array.array('i',[1,2,3,4])
print(my_array1)

array('i')
array('i', [1, 2, 3, 4])


In [12]:
import numpy as np
#Empty Array :: time complexity = O(1), space complexity = O(1)
np_array = np.array([], dtype=int)
print(np_array)
#time complexity = O(n), space complexity = O(n)
np_array1 = np.array([1,2,3,4])
print(np_array1)

[]
[1 2 3 4]


##### Insertion to Array

When we are insterting an element at a specific position using insert method,   
**time complexity** = depends on the number of the elements that needs to be shifted right = O(n)  
**space complexity** = O(1)

In [7]:
my_array1.insert(0,6)
my_array1.insert(10,7)
my_array1

array('i', [6, 1, 2, 3, 4, 7])

#### Traversal Operation
**time complexity** = O(n)   
**space complexity** = O(1), coz we don't need extra location to perform this operation.

In [8]:
#O(n) + O(1) = O(n)
def traverseArray(array):
    #O(n)
    for i in array:
        #O(1)
        print(i)

#### Accessing an element of Array
**time complexity** = O(1)  
**space complexity** = O(1)

In [9]:
#O(1)
def accessElement(array, index):
    #O(1)
    if index >= len(array):
        #O(1)
        print('Len is outside array length')
    else:
        #O(1)
        print(array[index])

#### Searching for an element of Array
**time complexity** = O(1)  
**space complexity** = O(1)

In [11]:
import array
my_array1 = array.array('i', [1,2,3,4,5])

def linear_search(arr, target):
    #O(1) = coz range function doesn't generate seq of integers, rather creates an iterator that can be used to produce numbers on demand.
    for i in range(len(arr)):
        #O(1)
        if arr[i] == target:
            #O(1)
            return i
    #O(1)
    return -1

print(linear_search(my_array1, 5))

4


#### Deleting an element from Array
When we delete an element form array, the next element will move to the place of deleted element and so on.  
**time complexity** = if last element : O(1) else O(n)  
**space complexity** = O(1)

#### Time and space complexity of One dimensional array
|            Operation               | Time Complexity | Space Complexity |
|------------------------------------|-----------------|------------------|
|Creating an empty array | O(1) | O(1) |
|Creating an array with elements | O(n) | O(n) |
|Inserting a value in an array | O(n) | O(1) |
|Traversing a given array | O(n) | O(1) |
|Accessing a given cell | O(1) | O(1) |
|Searching a given value | O(n) | O(1) |
|Deleting a given value | O(n) | O(1) |

In [19]:
from array import *

# 1. Create an array and traverse. 

my_array = array('i',[1,2,3,4,5])

for i in my_array:
    print(i)


# 2. Access individual elements through indexes
print("Step 2")
print(my_array[3])

# 3. Append any value to the array using append() method

print("Step 3")
my_array.append(6)
print(my_array)

# 4. Insert value in an array using insert() method
print("Step 4")
my_array.insert(3, 11)
print(my_array)


# 5. Extend python array using extend() method
print("Step 5")
my_array1 = array('i', [10,11,12])
my_array.extend(my_array1)
print(my_array)

# 6. Add items from list into array using fromlist() method
print("Step 6")
tempList = [20,21,22]
my_array.fromlist(tempList)
print(my_array)

# 7. Remove any array element using remove() method
print("Step 7")
my_array.remove(11)
print(my_array)

# 8. Remove last array element using pop() method
print("Step 8")
my_array.pop()
print(my_array)

# 9. Fetch any element through its index using index() method
print("Step 9")
print(my_array.index(21))

# 10. Reverse a python array using reverse() method
print("Step 10")
my_array.reverse()
print(my_array)

# 11. Get array buffer information through buffer_info() method
print("Step 11")
print(my_array.buffer_info())

# 12. Check for number of occurrences of an element using count() method
print("Step 12")
my_array.append(11)
print(my_array.count(11))
print(my_array)

# 13. Convert array to string using tostring() method
print("Step 13")
strTemp = my_array.tobytes()
print(strTemp)
ints = array('i')
ints.frombytes(strTemp)
print(ints)

# 14. Convert array to a python list with same elements using tolist() method
print("Step 14")
print(my_array.tolist())

# 15. Append a string to char array using fromstring() method


# 16. Slice Elements from an array
print("Step 16")
print(my_array[:])

1
2
3
4
5
Step 2
4
Step 3
array('i', [1, 2, 3, 4, 5, 6])
Step 4
array('i', [1, 2, 3, 11, 4, 5, 6])
Step 5
array('i', [1, 2, 3, 11, 4, 5, 6, 10, 11, 12])
Step 6
array('i', [1, 2, 3, 11, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 7
array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 8
array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21])
Step 9
10
Step 10
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])
Step 11
(139710998894192, 11)
Step 12
2
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])
Step 13
b'\x15\x00\x00\x00\x14\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x0b\x00\x00\x00'
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])
Step 14
[21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11]
Step 16
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])


### Two Dimensional Array
An array with a bunch of values having been declared with double index.

In [1]:
#O(mn), m= col, n=rows
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


#### Insertion
Addition of column / Addition of rows  
**Time complexity** = O(MN) = M: number of columns, N: number of rows

In [6]:
#O(mn), m= col, n=rows
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

newTwoDArray = np.insert(twoDArray, 0, [[1, 2, 3, 4]], axis=1)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [3]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

#O(1) , Space Complexity= O(1)
def accessElements(array, RowIdx, ColIdx):
    #O(1)
    if RowIdx >= len(array) and ColIdx >= len(array[0]):
        #O(1)
        print('Incorrect Index')
    #O(1)
    else:
        #O(1)
        print(array[RowIdx, ColIdx])

accessElements(twoDArray, 2, 3)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
8


#### Traversal 2D
**time complexity** = O(mn)  
**space complexity** = O(1)

In [5]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

#O(mn)
def traverseTDArray(array):
    #O(mn)
    for i in range(len(array)):
        #O(n)
        for j in range(len(array[0])):
            #O(1)
            print(array[i][j])
                    
traverseTDArray(twoDArray)                    

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


#### Searching 2D Array
**time complexity** = O(mn)  
**space complexity** = O(1)

In [8]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

#O(mn)
def searchTDArray(array, value):
    #O(mn)
    for i in range(len(array)):
        #O(n)
        for j in range(len(array[0])):
            #O(1)
            if array[i][j] == value:
                #O(1)
                return 'The value is located at index '+ str(i) + " , " + str(j)
    #O(1)
    return 'The element is not found'            
                    
searchTDArray(twoDArray, 8)                    

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


'The value is located at index 2 , 3'

#### Deletion from 2D Array
copying the original data without deleted column/row into a new array with new location  
**time complexity** = O(mn)  
**space complexity** = O(mn)

In [11]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

newTDArray = np.delete(twoDArray, 1, axis=0)
print(newTDArray)

new2DArray = np.delete(newTDArray, 0, axis = 1)
print(new2DArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[11 15 10  6]
 [12 17 12  8]
 [15 18 14  9]]
[[15 10  6]
 [17 12  8]
 [18 14  9]]


#### Time and space complexity of 2D array
|            Operation               | Time Complexity | Space Complexity |
|------------------------------------|-----------------|------------------|
|Creating an empty array | O(1) | O(1) |
|Creating an array with elements | O(mn) | O(mn) |
|Inserting a value in an array | O(mn) | O(mn) |
|Traversing a given array | O(mn) | O(1) |
|Accessing a given cell | O(1) | O(1) |
|Searching a given value | O(mn) | O(1) |
|Deleting a given value | O(mn) | O(mn) |

### When to use/avoid Arrays

When to use ::  
- To store multiple variables of same data type  
- Random Access  

When to avoid ::  
- Same data type elements  
- Reserve memory  

## Section 4 : Python Lists

#### Accessing/Traversing the list : time complexity - O(1), space complexity - O(1)

In [1]:
shoppingList = ['Milk', 'Cheese', 'Butter']

print('Milk' in shoppingList)

for i in range(len(shoppingList)):
    shoppingList[i] = shoppingList[i]+"+"
    print(shoppingList[i])
    
empty = []
for i in empty:
    print("I am empty")


True
Milk+
Cheese+
Butter+


#### Update/Insert : time complexity - O(1), space complexity - O(1)

In [19]:
myList = [1,2,3,4,5,6,7]
print(myList)

#O(1)
myList[0] = 0
#O(n)
myList.insert(4,15)
#O(1)
myList.append(55)
#O(n)
newList = [11,12,13,14]
myList.extend(newList)
#O(n)
newList = [['a','b','c','d']]
myList.extend(newList)
print(myList)

[1, 2, 3, 4, 5, 6, 7]
[0, 2, 3, 4, 15, 5, 6, 7, 55, 11, 12, 13, 14, ['a', 'b', 'c', 'd']]


#### Slice/Delete from a List : time complexity - O(n), space complexity - O(1)

In [26]:
myList = ['a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e']
#By default last element
#O(1)
myList.pop()
#O(n)
myList.pop(1)
print(myList)

#O(n)
del myList[4:]
print(myList)

#O(1)
myList.remove('a')
print(myList)

['a', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd']
['a', 'c', 'd', 'e']
['c', 'd', 'e']


#### Searching for an element in the List : time complexity - O(n), space complexity - O(1)

In [27]:
myList =  [10,20,30,40,50,60,70,80,90]

def linearSearchInList(list, value):
    for i in list:
        if i == value:
            return list.index(value)
    return 'The value does not exist in the list'

print(linearSearchInList(myList, 100))

The value does not exist in the list


####  List operations / functions : 

In [28]:
a,b = [1,2,3], [4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [29]:
a=[0]
print(a*4)

[0, 0, 0, 0]


In [33]:
a= [1,2,3,4,5,6]
print(max(a))
print(min(a))
print(sum(a))

6
1
21


In [ ]:
total = 0 
count = 0
while (True):
    inp = [input('Enter a number: ') ]
    if inp == 'done': break
    value = float(inp)
    total = total + value
    count = count + 1 
    average = total / count
					
print('Average:', average)

In [ ]:

numlist = list() 
while (True):
    inp = input('Enter a number: ') 
    if inp == 'done': break
    value = float(inp)
    numlist.append(value)
					
average = sum(numlist) / len(numlist) 
print('Average:', average)


#### Lists and Strings

In [3]:
a = 'spam'
b = list(a)
print(b)

a = 'spam spam spam'
b = a.split(' ')
print(b)

'-'.join(b)

['s', 'p', 'a', 'm']
['spam', 'spam', 'spam']


'spam-spam-spam'

#### Common list pitfalls and ways to avoid them

In [4]:
myList = [2, 4, 3, 1, 5, 7]
myList = myList.sort()
print(myList)

None


#### Lists vs Arrays
Similarities :
- Both data structures are mutable
- Both can be indexed and iterated through
- They both can be sliced

Diff :
- Arrays are optimized for arithmetic operations

#### Time and space complexity of Lists
|            Operation               | Time Complexity | Space Complexity |
|------------------------------------|-----------------|------------------|
|Creating an empty list | O(1) | O(1) |
|Creating a list with elements | O(n) | O(n) |
|Inserting a value in a list | O(n) | O(1) |
|Traversing a given list | O(n) | O(1) |
|Accessing a given cell in List| O(1) | O(1) |
|Searching a given value in List | O(n) | O(1) |
|Deleting a given value from List| O(1) | O(1) |

#### Quiz

In [7]:
data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
def fun(m):
    v = m[0][0]
    print(v)
 
    for row in m:
        print(f"row={row}")
        for element in row:
            print(f"element={element}")
            if v < element: 
                v = element
 
    return v
print(fun(data[0]))

1
row=[1, 2]
element=1
element=2
row=[3, 4]
element=3
element=4
4


In [8]:
fruit_list1 = ['Apple', 'Berry', 'Cherry', 'Papaya']
fruit_list2 = fruit_list1
fruit_list3 = fruit_list1[:]
 
fruit_list2[0] = 'Guava'
fruit_list3[1] = 'Kiwi'
 
sum = 0
for ls in (fruit_list1, fruit_list2, fruit_list3):
    print(ls)
    if ls[0] == 'Guava':
        sum += 1
    if ls[1] == 'Kiwi':
        sum += 20
 
print(sum)

['Guava', 'Berry', 'Cherry', 'Papaya']
['Guava', 'Berry', 'Cherry', 'Papaya']
['Apple', 'Kiwi', 'Cherry', 'Papaya']
22


In [9]:
arr = [1, 2, 3, 4, 5, 6]
for i in range(1, 6):
    arr[i - 1] = arr[i]
for i in range(0, 6): 
    print(arr[i], end = " ")

2 3 4 5 6 6 

In [15]:
a=[1,2,3,4,5]
print(a[3:0:-1])

[4, 3, 2]


In [25]:
a=[1,2,3,4,5,6,7,8,9]
a[::2]=10,20,30,40,50,60
print(a)

ValueError: attempt to assign sequence of size 6 to extended slice of size 5

In [22]:
import random
fruit=['apple', 'banana', 'papaya', 'cherry']
random.shuffle(fruit)
print(fruit)

['papaya', 'cherry', 'apple', 'banana']


In [23]:
arr = [[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 10, 11],
       [12, 13, 14, 15]]
for i in range(0, 4):
    print(arr[i].pop())

4
7
11
15


In [24]:
def f(value, values):
    v = 1
    values[0] = 44

t = 3
v = [1, 2, 3]
f(t, v)

print(t, v[0])

3 44


In [1]:
def missing_number(arr, n):
    if len(arr) != n:
        

SyntaxError: incomplete input (294177552.py, line 3)

In [2]:
class Youtube:
    def __init__(self, username, subscribers=0, subscriptions=0):
        self.username = username
        self.subscribers = subscribers
        self.subscriptions = subscriptions

    def subscribe(self, user):
        user.subscribers += 1
        self.subscriptions += 1

In [3]:
user1 = Youtube("World Affairs")
user2 = Youtube("Sandeep")

In [4]:
print(user1.subscribers)
print(user1.subscriptions)

print(user2.subscribers)
print(user2.subscriptions)

0
0
0
0


In [5]:
user1 = Youtube("World Affairs")
user2 = Youtube("Sandeep")
user1.subscribe(user2)

In [6]:
print(user1.subscribers)
print(user1.subscriptions)

print(user2.subscribers)
print(user2.subscriptions)

0
1
1
0


## Linked List

In [2]:
#O(1), O(1)
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

In [4]:
new_node = Node(10)
print(new_node)

In [14]:
#Empty Linked List = time Complextiy- O(1), Space Complexity- O(1)
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

#O(1)
class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

empty_linked_list = LinkedList()
print(empty_linked_list.length)

0


In [12]:
#Single Node Linked List
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self, value) -> None:
        new_node = Node(value)
        self.head = new_node
        self.tail = new_node
        self.length = 1

single_element_linkd_list = LinkedList(10)
print(single_element_linkd_list)
print(single_element_linkd_list.head)
print(single_element_linkd_list.tail)
print(single_element_linkd_list.head.value)
print(single_element_linkd_list.head.next)
print(single_element_linkd_list.tail.value)
print(single_element_linkd_list.tail.next)
print(single_element_linkd_list.length)

10
None
10
None
1


#### Insert an element at the end of Singly Linked List - Append Method

In [3]:
#When Linked list is empty
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

    #O(1), O(1)
    def append(self, value):
        #O(1)
        new_node = Node(value)
        #O(1)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.length += 1


In [4]:
new_linked_list = LinkedList()
new_linked_list.append(10)
new_linked_list.append(20)
print(new_linked_list.length)

2


#### Print Linked List- __str__

In [5]:
class Person:
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

new_person=Person("Raj", 30)
print(new_person)

In [7]:
class Person:
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

    def __str__(self):
        return f"Person {self.name} - {self.age}"

new_person=Person("Raj", 30)
print(new_person)

Person Raj - 30


In [ ]:
#When Linked list is empty
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

    #O(1), O(1)
    def append(self, value):
        #O(1)
        new_node = Node(value)
        #O(1)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.length += 1

    #O(1), O(1)
    def prepend(self,value):
        new_node = Node(value)
        if self.head is None or self.length == 0:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.next = self.head
            self.head = new_node
        self.length += 1

    def __str__(self):
        temp_node = self.head
        result = ''
        while temp_node is not None:
            result += str(temp_node.value)
            if temp_node.next is not None:
                result += ' -> '
            temp_node = temp_node.next
        return result


In [15]:
new_linked_list = LinkedList()
print(new_linked_list)
new_linked_list.append(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)


10 -> 20 -> 30


In [16]:
new_linked_list = LinkedList()
print(new_linked_list)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.prepend(40)
print(new_linked_list)


10 -> 20 -> 30
40 -> 10 -> 20 -> 30


#### Insert Method in Singly liniked List

In [1]:
#When Linked list is empty
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

    #O(1), O(1)
    def append(self, value):
        #O(1)
        new_node = Node(value)
        #O(1)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.length += 1

    #O(1), O(1)
    def prepend(self,value):
        new_node = Node(value)
        if self.head is None or self.length == 0:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.next = self.head
            self.head = new_node
        self.length += 1

    def __str__(self):
        temp_node = self.head
        result = ''
        while temp_node is not None:
            result += str(temp_node.value)
            if temp_node.next is not None:
                result += ' -> '
            temp_node = temp_node.next
        return result
    
    def insert(self, index, value):
        new_node = Node(value)
        temp_node = self.head
        for _ in range(index-1):
            temp_node = temp_node.next
        new_node.next = temp_node.next
        temp_node.next = new_node
        self.length += 1

In [2]:
new_linked_list = LinkedList()
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(1,50)
print(new_linked_list)

10 -> 20 -> 30
10 -> 50 -> 20 -> 30


In [3]:
#When index=0 still 50 is inserted at index=1
new_linked_list = LinkedList()
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(0,50)
print(new_linked_list)

10 -> 20 -> 30
10 -> 50 -> 20 -> 30


In [15]:
#When Linked list is empty
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

    #O(1), O(1)
    def append(self, value):
        #O(1)
        new_node = Node(value)
        #O(1)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.length += 1

    #O(1), O(1)
    def prepend(self,value):
        new_node = Node(value)
        if self.head is None or self.length == 0:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.next = self.head
            self.head = new_node
        self.length += 1

    def __str__(self):
        temp_node = self.head
        result = ''
        while temp_node is not None:
            result += str(temp_node.value)
            if temp_node.next is not None:
                result += ' -> '
            temp_node = temp_node.next
        return result
    
    #O(n), O(1)= coz no additional memory required, that depends on the size of insert element
    def insert(self, index, value):
        new_node = Node(value)
        #In our case -ve index and index greater than length is not allowed
        if index < 0 or index > self.length:
            return False
        if self.length == 0 or self.head == None:
            self.head = new_node
            self.tail = new_node
        elif index == 0:
            new_node.next = self.head
            self.head = new_node
        else:
            temp_node = self.head
            #O(n) rest all statements here O(1)
            for _ in range(index-1):
                temp_node = temp_node.next
            new_node.next = temp_node.next
            temp_node.next = new_node
        self.length += 1
        return True

In [12]:
#Now index=0,  50 will be inserted at head
new_linked_list = LinkedList()
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(0,50)
print(new_linked_list)

10 -> 20 -> 30
50 -> 10 -> 20 -> 30


In [14]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(0,50)
print(new_linked_list)

10 -> 50 -> 20 -> 30
50 -> 10 -> 50 -> 20 -> 30


#### Traversal of Singly Linked List

In [18]:
#When Linked list is empty
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

    #O(1), O(1)
    def append(self, value):
        #O(1)
        new_node = Node(value)
        #O(1)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.length += 1

    #O(1), O(1)
    def prepend(self,value):
        new_node = Node(value)
        if self.head is None or self.length == 0:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.next = self.head
            self.head = new_node
        self.length += 1

    def __str__(self):
        temp_node = self.head
        result = ''
        while temp_node is not None:
            result += str(temp_node.value)
            if temp_node.next is not None:
                result += ' -> '
            temp_node = temp_node.next
        return result
    
    #O(n), O(1)= coz no additional memory required, that depends on the size of insert element
    def insert(self, index, value):
        new_node = Node(value)
        #In our case -ve index and index greater than length is not allowed
        if index < 0 or index > self.length:
            return False
        if self.length == 0 or self.head == None:
            self.head = new_node
            self.tail = new_node
        elif index == 0:
            new_node.next = self.head
            self.head = new_node
        else:
            temp_node = self.head
            #O(n) rest all statements here O(1)
            for _ in range(index-1):
                temp_node = temp_node.next
            new_node.next = temp_node.next
            temp_node.next = new_node
        self.length += 1
        return True
    
    #O(n), O(1)
    def traverse(self):
        current = self.head
        #while current is not None:
        while current:
            print(current.value)
            current = current.next

In [19]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(0,50)
print(new_linked_list)
new_linked_list.traverse()

10 -> 50 -> 20 -> 30
50 -> 10 -> 50 -> 20 -> 30
50
10
50
20
30


#### Search Method in Singly Linked List

In [2]:
#When Linked list is empty
class Node:
    def __init__(self, value) -> None:
        self.value = value
        self.next = None

class LinkedList:
    def __init__(self) -> None:
        self.head = None
        self.tail = None
        self.length = 0

    #O(1), O(1)
    def append(self, value):
        #O(1)
        new_node = Node(value)
        #O(1)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.length += 1

    #O(1), O(1)
    def prepend(self,value):
        new_node = Node(value)
        if self.head is None or self.length == 0:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.next = self.head
            self.head = new_node
        self.length += 1

    def __str__(self):
        temp_node = self.head
        result = ''
        while temp_node is not None:
            result += str(temp_node.value)
            if temp_node.next is not None:
                result += ' -> '
            temp_node = temp_node.next
        return result
    
    #O(n), O(1)= coz no additional memory required, that depends on the size of insert element
    def insert(self, index, value):
        new_node = Node(value)
        #In our case -ve index and index greater than length is not allowed
        if index < 0 or index > self.length:
            return False
        if self.length == 0 or self.head == None:
            self.head = new_node
            self.tail = new_node
        elif index == 0:
            new_node.next = self.head
            self.head = new_node
        else:
            temp_node = self.head
            #O(n) rest all statements here O(1)
            for _ in range(index-1):
                temp_node = temp_node.next
            new_node.next = temp_node.next
            temp_node.next = new_node
        self.length += 1
        return True
    
    #O(n), O(1)
    def traverse(self):
        current = self.head
        #while current is not None:
        while current:
            print(current.value)
            current = current.next

    #time Complexity = O(n), space = O(1)
    def search(self, target):
        current = self.head
        #to get the index
        idx = 0
        #while current is not None:
        while current:
            if current.value == target:
                return idx
            current = current.next
            idx += 1
        return -1
            

In [27]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(0,50)
print(new_linked_list.search(30))
print(new_linked_list.search(36))

10 -> 50 -> 20 -> 30
4
-1


#### Get Method in Singly Linked List

In [3]:
#O(n), O(1)
def get(LinkedList, idx):
    if idx == -1:
        LinkedList.tail
    elif idx < -1 or idx >= LinkedList.length:
        return None
    current = LinkedList.head
    for _ in range(idx):
        current = current.next
    return current

In [45]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
new_linked_list.insert(0,50)
get(new_linked_list,2)

10 -> 50 -> 20 -> 30


In [46]:
get(new_linked_list,2).value

50

In [43]:
get(new_linked_list,-2)

In [44]:
get(new_linked_list,20)

In [47]:
#O(n), O(1)
def get(LinkedList, idx):
    if idx == -1:
        LinkedList.tail.value
    elif idx < -1 or idx >= LinkedList.length:
        return None
    current = LinkedList.head
    for _ in range(idx):
        current = current.next
    return current.value

In [48]:
get(new_linked_list,2)

50

In [49]:
get(new_linked_list,20)

In [50]:
get(new_linked_list,-2)

In [52]:
#### Set/Update Method in Singly Linked List

In [4]:
#O(n), O(1)
def get(LinkedList, idx):
    if idx == -1:
        LinkedList.tail
    elif idx < -1 or idx >= LinkedList.length:
        return None
    current = LinkedList.head
    for _ in range(idx):
        current = current.next
    return current

In [54]:
def set_value(LinkedList, index, value):
    temp = get(LinkedList, index)
    if temp:
        temp.value = value
        return True
    return False

In [56]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)
set_value(new_linked_list,2,56)
print(new_linked_list)

10 -> 50 -> 20 -> 30
10 -> 50 -> 56 -> 30


#### Pop First Method in Singly Linked List

In [67]:
def pop_first(LinkedList):
    popped_node = LinkedList.head
    LinkedList.head = LinkedList.head.next
    popped_node.next = None
    LinkedList.length -= 1
    return popped_node

In [68]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)

10 -> 50 -> 20 -> 30


In [69]:
pop_first(new_linked_list).value

10

In [70]:
print(new_linked_list)

50 -> 20 -> 30


In [71]:
new_linked_list = LinkedList()
new_linked_list.prepend(10)
print(new_linked_list)

10


In [72]:
print(pop_first(new_linked_list))

In [73]:
print(new_linked_list.tail.value)

10


In [80]:
def pop_first(LinkedList):
    popped_node = LinkedList.head
    if LinkedList.length > 1:
        LinkedList.head = LinkedList.head.next
    elif LinkedList.length == 1:
        LinkedList.head = None
        LinkedList.tail = None
    else:
        pass
    popped_node.next = None
    LinkedList.length -= 1
    return popped_node

In [81]:
new_linked_list = LinkedList()
new_linked_list.prepend(10)
print(new_linked_list)

10


In [82]:
print(pop_first(new_linked_list))

In [83]:
print(new_linked_list.tail.value)

AttributeError: 'NoneType' object has no attribute 'value'

In [84]:
print(pop_first(new_linked_list))

AttributeError: 'NoneType' object has no attribute 'next'

In [5]:
#O(1), O(1)
def pop_first(LinkedList):
    popped_node = LinkedList.head
    if LinkedList.length > 1:
        LinkedList.head = LinkedList.head.next
    elif LinkedList.length == 1:
        LinkedList.head = None
        LinkedList.tail = None
    else:
        return None
    popped_node.next = None
    LinkedList.length -= 1
    return popped_node

In [86]:
new_linked_list = LinkedList()
new_linked_list.prepend(10)
print(new_linked_list)

10


In [87]:
print(pop_first(new_linked_list))

In [88]:
print(pop_first(new_linked_list))

None


#### Pop Method in Singly Linked List

In [6]:
#O(n), O(1)
def pop(LinkedList):
    if LinkedList.length == 0:
        return None
    popped_node = LinkedList.tail
    if LinkedList.length == 1:
        LinkedList.head = LinkedList.tail = None
    else:
        temp = LinkedList.head
        while temp.next is not LinkedList.tail:
            temp = temp.next
        LinkedList.tail = temp
        temp.next = None
    LinkedList.length -= 1
    return popped_node


In [91]:
new_linked_list = LinkedList()
new_linked_list.prepend(10)
print(new_linked_list)

10


In [92]:
print(pop(new_linked_list))

In [93]:
print(new_linked_list)

#### Remove Method in Singly Linked List

In [42]:
#O(1), O(1)
def remove(LinkedList, index):
    if index == 0:
        return pop_first(LinkedList)
    if index >= LinkedList.length or index < 0:
        return None 
    if index == LinkedList.length:
        return pop(LinkedList)
    prev_node = get(LinkedList, index -1)
    popped_node = prev_node.next
    prev_node.next = popped_node.next
    popped_node.next = None
    LinkedList.length -= 1
    return popped_node

In [43]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)

10 -> 50 -> 20 -> 30


In [44]:
remove(new_linked_list,1)

In [45]:
print(new_linked_list)

10 -> 20 -> 30


In [46]:
remove(new_linked_list,0)

In [47]:
print(new_linked_list)

20 -> 30


In [48]:
remove(new_linked_list,-1)

In [49]:
print(new_linked_list)

20 -> 30


In [50]:
remove(new_linked_list,1)

In [51]:
print(new_linked_list)

20


#### Delete All Nodes of Singly Linked List

In [52]:
#O(1), O(1)
def delete_all(LinkedList):
    LinkedList.head = None
    LinkedList.tail = None
    LinkedList.length = 0

In [53]:
new_linked_list = LinkedList()
new_linked_list.insert(0,50)
new_linked_list.prepend(10)
new_linked_list.append(20)
new_linked_list.append(30)
print(new_linked_list)

10 -> 50 -> 20 -> 30


In [54]:
delete_all(LinkedList)

In [58]:
print(LinkedList.length)

0


#### Time and Space Complexity of Singly Linked List

| SLL Operation | Time Complexity | Space Complexity|
|---------------|-----------------|-----------------|
|Create   |O(1)|O(1)|
|Append   |O(1)|O(1)|
|Prepend   |O(1)|O(1)|
|Insert   |O(n)|O(1)|
|Search   |O(n)|O(1)|
|Traverse   |O(n)|O(1)|
|Get   |O(n)|O(1)|
|Set   |O(n)|O(1)|
|Pop First   |O(1)|O(1)|
|Pop   |O(1)|O(1)|
|Remove   |O(n)|O(1)|
|Delete all nodes   |O(1)|O(1)|